### ISSUE TITLE
AMC fails to connect after panic

### ISSUE THREAD

**Issue by leedavis81** [aerospike-community/amc#34]
I'm running a benchmark tool and using AMC to observe throughput, after a few seconds there the tool appears to error with the following logged:

```
amc-dev          | unknown time zone GMT
amc-dev          | panic: time: missing Location in call to Time.In
amc-dev          |
amc-dev          | goroutine 22 [running]:
amc-dev          | time.Time.In(...)
amc-dev          | 	/usr/local/go/src/time/time.go:1099
amc-dev          | github.com/aerospike-community/amc/models.(*Node).parseLatenciesInfo(0xc0002c81e0, 0xc00024821b, 0x9d, 0xa, 0xc0002a83e8)
amc-dev          | 	/home/zohar/go/src/github.com/aerospike-community/amc/models/node.go:1197 +0x1b27
amc-dev          | github.com/aerospike-community/amc/models.(*Node).update(0xc0002c81e0, 0x0, 0x0)
amc-dev          | 	/home/zohar/go/src/github.com/aerospike-community/amc/models/node.go:172 +0xb45
amc-dev          | github.com/aerospike-community/amc/models.(*Cluster).updateStats.func1(0xc0003c47f0, 0xc0002c81e0)
amc-dev          | 	/home/zohar/go/src/github.com/aerospike-community/amc/models/cluster.go:816 +0x53
amc-dev          | created by github.com/aerospike-community/amc/models.(*Cluster).updateStats
amc-dev          | 	/home/zohar/go/src/github.com/aerospike-community/amc/models/cluster.go:814 +0x10e

Using version amc:4.1.3

reverting to 4.0.27 resolved the issue

**Comment by bilxio** [comment]
catch this panic information either

> version amc:4.1.3

**Comment by psladek-seekr** [comment]
Should be able to install tzdata or something similar and configure for your needs. Would need to build on top of the docker image etc.

`apt-get update; apt-get install -y tzdata`
